settings:
  # 产生矿物时播放的音效, 支持 PlaceholderAPI 实现随机音调
  # 格式: 声音名称-音量-音调
  spawn-sound: 'ENTITY_ITEM_PICKUP-1.0-1.0'


groups:
  - spawns:
      - 'COBBLESTONE:60'
      - 'STONE:20'
      - 'DIORITE:1'
      - 'GRANITE:1'
      - 'ANDESITE:1'
      - 'GRAVEL:5'
      - 'DIRT:5'
      - 'COAL_ORE:10'
      - 'IRON_ORE:10'
      - 'GOLD_ORE:10'
      - 'LAPIS_ORE:5'
      - 'REDSTONE_ORE:20'
      - 'DIAMOND_ORE:15'
      - 'EMERALD_ORE:5'
    enabled-world:
      - 'bskyblock_world'