settings:
  # Sound effects played when minerals are generated, support PlaceholderAPI to achieve random tones
  # Format: Sound Name-Volume-Pitch
  # 产生矿物时播放的音效, 支持 PlaceholderAPI 实现随机音调
  # 格式: 声音名称-音量-音调
  spawn-sound: 'ENTITY_ITEM_PICKUP-1.0-1.0'


groups:
  # Ores type and chance
  # Format: material:chance
  # 刷矿种类和概率
  # 格式: material:chance
  - spawns:
      - 'COBBLESTONE:60'
      - 'STONE:20'
      - 'DIORITE:1'
      - 'GRANITE:1'
      - 'ANDESITE:1'
      - 'GRAVEL:5'
      - 'DIRT:5'
      - 'COAL_ORE:10'
      - 'IRON_ORE:10'
      - 'GOLD_ORE:10'
      - 'LAPIS_ORE:5'
      - 'REDSTONE_ORE:20'
      - 'DIAMOND_ORE:15'
      - 'EMERALD_ORE:5'
    # 启用的世界, 指该刷石机仅在以下世界才能发挥作用.
    # The enabled world means that the ore producer can only play a role in the following worlds.
    enabled-world:
      - 'bskyblock_world'