name: MineralSpawner
version: ${project.version}
main: me.scoretwo.mineralspawner.bukkit.MineralSpawner
author: Score2
api-version: 1.13
softdepend:
  - KotlinAPI
permissions:
  mineralspawner.admin:
    default: op